using System.Collections.Generic;

public class Fetishes
{
	public static List<string> fetishes = new List<string>();

	public static List<string> fetishDescriptions = new List<string>();

	public static List<float> fetishDefaultValues = new List<float>();

	public static void init()
	{
		Fetishes.fetishes = new List<string>();
		Fetishes.fetishDescriptions = new List<string>();
		Fetishes.fetishDefaultValues = new List<float>();
		Fetishes.fetishDefaultValues.Add(-1f);
		Fetishes.fetishes.Add("CATEGORY_Display Options");
		Fetishes.fetishDescriptions.Add(string.Empty);
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Animal-Style Genitals");
		Fetishes.fetishDescriptions.Add("Genitals that resemble their animal counterparts.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Squirting");
		Fetishes.fetishDescriptions.Add("Test subjects that ejaculate vaginally.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Inflation / Bulging");
		Fetishes.fetishDescriptions.Add("Causing a test subject's stomach to swell when being penetrated by a large object, or when filled by too much cum.");
		Fetishes.fetishDefaultValues.Add(-1f);
		Fetishes.fetishes.Add("CATEGORY_Personal Involvement");
		Fetishes.fetishDescriptions.Add(string.Empty);
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Personal Interaction");
		Fetishes.fetishDescriptions.Add("Interacting with a test subject using your own body, rather than using toys or machines.");
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Handjobs");
		Fetishes.fetishDescriptions.Add("Sexual stimulation of a test subject using your hand[s].");
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Oral Sex");
		Fetishes.fetishDescriptions.Add("Sexual stimulation of a test subject using your mouth.");
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Vaginal Penetration");
		Fetishes.fetishDescriptions.Add("Vaginal penetration of a test subject.");
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Anal Penetration");
		Fetishes.fetishDescriptions.Add("Anal penetration of a test subject.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Power Bottom");
		Fetishes.fetishDescriptions.Add("Being penetrated by a test subject, often while they are unable to refuse.");
		Fetishes.fetishDefaultValues.Add(1f);
		Fetishes.fetishes.Add("Rimming");
		Fetishes.fetishDescriptions.Add("Oral stimulation of a test subject's anus.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Footplay");
		Fetishes.fetishDescriptions.Add("Sexually stimulating test subjects by interacting with their feet, or having them interact with your feet.");
		Fetishes.fetishDefaultValues.Add(-1f);
		Fetishes.fetishes.Add("CATEGORY_Toys");
		Fetishes.fetishDescriptions.Add(string.Empty);
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Sex Toys");
		Fetishes.fetishDescriptions.Add("Small, handheld toys and gadgets designed for sexual stimulation, often through vibration penetration, or gyration.");
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Sex Machines");
		Fetishes.fetishDescriptions.Add("Large, mechanical devices designed for sexual stimulation, often through vibration, penetration, or gyration.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Electrostimulation");
		Fetishes.fetishDescriptions.Add("Sexual stimulation through the use of electricity.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Spanking");
		Fetishes.fetishDescriptions.Add("Spanking test subjects.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Tickling");
		Fetishes.fetishDescriptions.Add("Tickling a test subject.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Hyposis / Mind Control");
		Fetishes.fetishDescriptions.Add("Using magic or technology to alter or reprogram a person's sexual preferences and willingness, either temporarily or permanently.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Magic");
		Fetishes.fetishDescriptions.Add("Sexual stimulation through the use of seemingly-magical means.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Autoeroticism");
		Fetishes.fetishDescriptions.Add("Causing or allowing a test subject to sexual stimulate themselve, often through the use of portal devices.");
		Fetishes.fetishDefaultValues.Add(1f);
		Fetishes.fetishes.Add("Extreme Penetration");
		Fetishes.fetishDescriptions.Add("Penetration of test subjects with multiple objects, or very large objects.");
		Fetishes.fetishDefaultValues.Add(1f);
		Fetishes.fetishes.Add("Impact Play");
		Fetishes.fetishDescriptions.Add("Caning, paddling, whipping, or slapping test subjects.");
		Fetishes.fetishDefaultValues.Add(1f);
		Fetishes.fetishes.Add("Wax / Heat Play");
		Fetishes.fetishDescriptions.Add("The use of hot wax and other heat-based toys on test subjects.");
		Fetishes.fetishDefaultValues.Add(1f);
		Fetishes.fetishes.Add("Ice / Cold Play");
		Fetishes.fetishDescriptions.Add("The use of ice and other cold-based toys on test subjects.");
		Fetishes.fetishDefaultValues.Add(-1f);
		Fetishes.fetishes.Add("CATEGORY_BDSM");
		Fetishes.fetishDescriptions.Add(string.Empty);
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Edging");
		Fetishes.fetishDescriptions.Add("Drawn-out sexual sessions where a test subject is kept near orgasm for a long time before allowing them to climax.");
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Milking");
		Fetishes.fetishDescriptions.Add("The extraction of sexual fluids from a test subject, often for storage/reuse, with little or no regard for their comfort or pleasure.");
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Overstimulation");
		Fetishes.fetishDescriptions.Add("Sexual stimulation of a test subject who is abnormally sensitive because they have recently had an orgasm.");
		Fetishes.fetishDefaultValues.Add(3f);
		Fetishes.fetishes.Add("Forced Interaction");
		Fetishes.fetishDescriptions.Add("Two or more test subjects being forced to interact sexually.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Denial / Ruined Orgasms");
		Fetishes.fetishDescriptions.Add("Sexual sessions where a test subject isn't allowed to orgasm, or is punished for having an orgasm.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Humiliation");
		Fetishes.fetishDescriptions.Add("Putting test subjects on public display, often in humiliating or compromising poses, or while wearing humiliating attire.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Public Use");
		Fetishes.fetishDescriptions.Add("Allowing test subjects to be used for sexual gratification by anyone who passes by.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Gangbang");
		Fetishes.fetishDescriptions.Add("Allowing a test subject to be used by several people.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Heavy Bondage / Mummification");
		Fetishes.fetishDescriptions.Add("Extreme restraint of test subjects, often through the use of vacuum sealing or full-body restraints.");
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Sensory Deprivation");
		Fetishes.fetishDescriptions.Add("Preventing test subjects from being able to see or hear.");
		Fetishes.fetishDefaultValues.Add(1f);
		Fetishes.fetishes.Add("Chastity");
		Fetishes.fetishDescriptions.Add("Devices that restrict a test subject's penis from becoming fully erect.");
		Fetishes.fetishDefaultValues.Add(-1f);
		Fetishes.fetishes.Add("CATEGORY_Body Play");
		Fetishes.fetishDescriptions.Add(string.Empty);
		Fetishes.fetishDefaultValues.Add(2f);
		Fetishes.fetishes.Add("Sizeplay");
		Fetishes.fetishDescriptions.Add("Sexual encounters between two people who are very different in size, and chemicals/devices that modify a character's size.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Hyper/Growth (Sex Organs)");
		Fetishes.fetishDescriptions.Add("Genitals or breasts that are abnormally large, or chemicals/devices that modify their size.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Hyper/Growth (Muscle)");
		Fetishes.fetishDescriptions.Add("Muscles that are abnormally large or well-defined, or chemicals/devices that modify musculature.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Hyper/Growth (Obesity)");
		Fetishes.fetishDescriptions.Add("Characters that are abnormally obese, or chemicals/devices that modify obesity.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Gender Transformation");
		Fetishes.fetishDescriptions.Add("Chemicals and devices that alter a test subject's sex organs and gender characteristics.");
		Fetishes.fetishDefaultValues.Add(-1f);
		Fetishes.fetishes.Add("CATEGORY_Niche Fetishes");
		Fetishes.fetishDescriptions.Add(string.Empty);
		Fetishes.fetishDefaultValues.Add(1f);
		Fetishes.fetishes.Add("Sleeping");
		Fetishes.fetishDescriptions.Add("Sexual stimulation of test subjects who are asleep, often with the goal of not waking them up.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Sounding");
		Fetishes.fetishDescriptions.Add("The insertion of rods and other sounding apparatus into a test subject's urethra.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Watersports");
		Fetishes.fetishDescriptions.Add("The use of urine during sex, either by urinating on a test subject, or by causing a test subject to urinate unwillingly.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Breathplay");
		Fetishes.fetishDescriptions.Add("Temporarily restricting a test subject's ability to breathe.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Genital Torture");
		Fetishes.fetishDescriptions.Add("The use of tools and actions specifically designed to inflict pain on a test subject's genitals.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Lactation");
		Fetishes.fetishDescriptions.Add("The extraction of milk from a test subject's breasts.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Impregnation");
		Fetishes.fetishDescriptions.Add("Causing test subjects with vaginas to become impregnated via insemination.");
		Fetishes.fetishDefaultValues.Add(0f);
		Fetishes.fetishes.Add("Material Transformation");
		Fetishes.fetishDescriptions.Add("The transformation of subjects into other materials, often latex or slime.");
	}
}
